# Generated by Django 3.2.7 on 2025-05-26 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='task_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'zip', 'jpg', 'png'])]),
        ),
    ]
